name: certbot
services:
  certbot:
    command: ${COMMAND}
    container_name: certbot
    environment:
      TZ: Europe/Berlin
    image: certbot/certbot
    networks:
      certbot: null
    ports:
      - mode: ingress
        target: 80
        published: "8080"
        protocol: tcp
    restart: "no"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: /docker/certbot/etc/letsencrypt
        target: /etc/letsencrypt
        bind:
          create_host_path: true
      - type: bind
        source: /docker/certbot/var/lib/letsencrypt
        target: /var/lib/letsencrypt
        bind:
          create_host_path: true
      - type: bind
        source: /docker/certbot/var/log/letsencrypt
        target: /var/log/letsencrypt
        bind:
          create_host_path: true
networks:
  certbot:
    name: certbot_certbot
