name: homeassistant
services:
  homeassistant:
    container_name: homeassistant
    environment:
      TZ: Europe/Berlin
    hostname: homeassistant
    healthcheck:
      test:
      - CMD-SHELL
      - curl http://127.0.0.1:8123 -s -o /dev/null > /dev/null 2>&1
      start_period: 10s
    image: homeassistant/home-assistant:latest
    network_mode: host
    restart: unless-stopped
    volumes:
    - type: bind
      source: /docker/homeassistant/config
      target: /config
      bind:
        create_host_path: true
  nginx:
    container_name: nginx
#    depends_on:
#      homeassistant:
#        condition: service_healthy
#        required: true
    environment:
      TZ: Europe/Berlin
    hostname: nginx
    healthcheck:
      test:
      - CMD-SHELL
      - curl http://127.0.0.1 -s -o /dev/null > /dev/null 2>&1
    image: nginx
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 200M
        reservations:
          cpus: '0.50'
          memory: 100M
    network_mode: host
    restart: unless-stopped
    volumes:
    - type: bind
      source: /docker/nginx/conf.d
      target: /etc/nginx/conf.d
      bind:
        create_host_path: true
