api:
  encryption:
    key: !secret 'api_encryption_key'

ota:
  - platform: esphome
    password: !secret 'ota_password'

network:
  enable_ipv6: true

wifi:
  ap:
    ssid: ${devicename}
    password: !secret 'wifi_ap_password'
  networks:
    - ssid: !secret 'wifi_networks_ssid'
      password: !secret 'wifi_networks_password'

captive_portal: {}

web_server:
  port: 80

time:
  - platform: homeassistant
    id: time_homeassistant
    timezone: Europe/Berlin
