font:
- file:
    family: Roboto
    type: gfonts
  id: roboto_small
  size: 14
  glyphs: '!"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/³µä'
- file:
    family: Roboto
    type: gfonts
  id: roboto
  size: 20
  glyphs: '!"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/³µä'
