name: lemonpi
services:
  homeassistant:
    container_name: homeassistant
    environment:
      TZ: Europe/Berlin
    hostname: homeassistant
    healthcheck:
      test:
        - CMD-SHELL
        - curl http://127.0.0.1:8123 -s -o /dev/null > /dev/null 2>&1
    image: homeassistant/home-assistant:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - /docker/homeassistant/config:/config
  nginx:
    container_name: nginx
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 50M
    environment:
      TZ: Europe/Berlin
    hostname: nginx
    healthcheck:
      test:
        - CMD-SHELL
        - curl http://127.0.0.1 -s -o /dev/null > /dev/null 2>&1
        - curl https://127.0.0.1 -s -o /dev/null > /dev/null 2>&1
    image: nginx
    network_mode: host
    restart: unless-stopped
    volumes:
      - /docker/nginx/conf.d:/etc/nginx/conf.d
  octoprint:
    container_name: octoprint
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
#      - /dev/video0:/dev/video0
    environment:
#      CAMERA_DEV: /dev/video0
#      ENABLE_MJPG_STREAMER: "true"
#      MJPG_STREAMER_INPUT: -y -n -r 1280x720
      TZ: Europe/Berlin
    hostname: octoprint
    healthcheck:
      test:
        - CMD-SHELL
        - curl http://127.0.0.1 -s -o /dev/null > /dev/null 2>&1
    image: octoprint/octoprint
    networks:
      octoprint: null
    ports:
      - 88:80
    restart: unless-stopped
    volumes:
      - /docker/octoprint/octoprint:/octoprint
  minecraft:
    container_name: minecraft
    environment:
      TZ: Europe/Berlin
      EULA: "TRUE"
#      ICON: http://..../some/image.png
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
    hostname: minecraft
    image: itzg/minecraft-server
    networks:
      minecraft: null
    ports:
      - 25565:25565
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /docker/minecraft/data:/data
networks:
  octoprint:
    name: octoprint
    driver_opts:
      com.docker.network.bridge.name: octoprint
    enable_ipv6: true
  minecraft:
    name: minecraft
    driver_opts:
      com.docker.network.bridge.name: minecraft
    enable_ipv6: true

