substitutions:
  devicename: basement
  comment: Gas und Strom
  name: woke.basement
  version: 1.0.0
  logger: INFO
  status_led: GPIO5
  tx_pin: GPIO17
  rx_pin: GPIO16
  binary_sensor_gas: GPIO21

<<: !include common/esphome.yaml

esp32:
  board: lolin32
#  board: wemos_d1_mini32

globals:
- id: total_pulses
  type: int
  initial_value: '0'

logger:
  <<: !include common/logger.yaml

uart:
- tx_pin:
    number: ${tx_pin}
  rx_pin:
    number: ${rx_pin}
  baud_rate: 9600

text_sensor:
- <<: !include common/text_sensor.yaml
- platform: sml
  name: Herstelleridentifikation
  obis_code: 129-129:199.130.3

status_led:
  pin:
    number: ${status_led}
    inverted: true

sensor:
- <<: !include common/sensor_uptime.yaml
- <<: !include common/sensor_wifi_signal.yaml
- platform: template
  name: Gasverbrauch
  device_class: gas
  update_interval: 10s
  unit_of_measurement: m³
  state_class: total_increasing
  icon: mdi:fire
  accuracy_decimals: 2
  lambda: !lambda |-
    return id(total_pulses) * 0.01;
- platform: sml
  name: Zählerstand zu +A, tariflos
  obis_code: 1-0:1.8.0
  unit_of_measurement: Wh
  accuracy_decimals: 2
  device_class: energy
  state_class: total_increasing
  filters:
  - multiply: 0.00001
- platform: sml
  name: Zählerstand zu -A, tariflos
  obis_code: 1-0:2.8.0
  unit_of_measurement: Wh
  accuracy_decimals: 2
  device_class: energy
  state_class: total_increasing
  filters:
  - multiply: 0.00001
- platform: sml
  name: Summe der Momentan-Leistungen in allen Phasen
  obis_code: 1-0:16.7.0
  unit_of_measurement: W
  accuracy_decimals: 2
  device_class: power
  state_class: measurement
  filters:
  - multiply: 0.01
- platform: sml
  name: Momentane Leistung in Phase L1
  obis_code: 1-0:36.7.0
  unit_of_measurement: W
  accuracy_decimals: 2
  device_class: power
  state_class: measurement
  filters:
  - multiply: 0.01
- platform: sml
  name: Momentane Leistung in Phase L2
  obis_code: 1-0:56.7.0
  unit_of_measurement: W
  accuracy_decimals: 2
  device_class: power
  state_class: measurement
  filters:
  - multiply: 0.01
- platform: sml
  name: Momentane Leistung in Phase L3
  obis_code: 1-0:76.7.0
  unit_of_measurement: W
  accuracy_decimals: 2
  device_class: power
  state_class: measurement
  filters:
  - multiply: 0.01

binary_sensor:
- <<: !include common/binary_sensor_status.yaml
- platform: gpio
  pin:
    number: ${binary_sensor_gas}
    inverted: true
    mode:
      input: true
      pullup: true
  name: Impuls
  filters:
  - delayed_on: 100ms
  on_press:
  - then:
    - lambda: !lambda |-
        id(total_pulses) += 1;

sml:

<<: !include common/base.yaml
