substitutions:
  devicename: livingroom
  comment: illuminance
  name: woke.livingroom
  version: 2.2.3
  logger: INFO
  sda_pin: GPIO2
  scl_pin: GPIO1
  button_pin: GPIO41
  ir_pin: GPIO4
  rpg_pin: GPIO35
  illuminance: illuminance

esphome:
  <<: !include common/esphome.yaml

esp32:
#  board: esp32-s3-devkitc-1
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    version: latest
    platform_version: 6.7.0

logger:
  <<: !include common/logger.yaml

text_sensor:
- <<: !include common/text_sensor_version.yaml
- <<: !include common/text_sensor_wifi_info.yaml

sensor:
- <<: !include common/sensor_uptime.yaml
- <<: !include common/sensor_wifi_signal.yaml
- platform: bh1750
  name: ${illuminance}
  id: sensor_bh1750_illuminance
  icon: mdi:sun-wireless-outline

binary_sensor:
- <<: !include common/binary_sensor_status.yaml

button:
- <<: !include common/restart.yaml

light:
- platform: neopixelbus
  variant: WS2811
  pin: ${rpg_pin}
  num_leds: 1
  id: rgbled
- platform: status_led
  id: statusled
  output: statusoutput

output:
- platform: template
  id: statusoutput
  write_action:
    then:
    - if:
        condition:
          lambda: !lambda |-
            return state == 0;
        then:
        - light.turn_on:
            id: rgbled
            red: 0.0
            green: 1.0
            blue: 0.0
            brightness: 30%
        else:
        - light.turn_on:
            id: rgbled
            red: 1.0
            green: 0.0
            blue: 0.0
            brightness: 30%
  type: binary

<<: !include common/base.yaml
<<: !include common/i2c.yaml
