substitutions:
  devicename: livingroom
  comment: illuminance
  name: woke.livingroom
  version: 2.2.1
  logger: INFO
  sda_pin: GPIO2
  scl_pin: GPIO1
  button_pin: GPIO41
  ir_pin: GPIO4
  rpg_pin: GPIO35
  illuminance: illuminance

<<: !include common/base.yaml
<<: !include common/i2c.yaml

esp32:
  board: esp32-s3-devkitc-1

logger:
  <<: !include common/logger.yaml

text_sensor:
- <<: !include common/text_sensor_version.yaml
- <<: !include common/text_sensor_wifi_info.yaml

sensor:
- <<: !include common/sensor_uptime.yaml
- <<: !include common/sensor_wifi_signal.yaml
- platform: bh1750
  name: ${illuminance}
  id: sensor_bh1750_illuminance
  icon: mdi:sun-wireless-outline

binary_sensor:
- <<: !include common/binary_sensor_status.yaml
