name: esphome
services:
  basement:
    command:
      - ${COMMAND}
      - basement.yaml
    container_name: basement
    environment:
      TZ: Europe/Berlin
    image: esphome/esphome:latest
    network_mode: host
    restart: "no"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ${PWD}/config
        target: /config
        bind:
          create_host_path: true
