name: esphome
services:
  basement:
    command:
    - ${COMMAND}
    - basement.yaml
    container_name: basement
    environment:
      TZ: Europe/Berlin
    hostname: basement
    image: esphome/esphome:latest
    network_mode: host
    restart: "no"
    volumes:
    - type: bind
      source: ./config
      target: /config
      bind:
        create_host_path: true
  livingroom:
    command:
    - ${COMMAND}
    - livingroom.yaml
    container_name: livingroom
    environment:
      TZ: Europe/Berlin
    hostname: livingroom
    image: esphome/esphome:latest
    network_mode: host
    restart: "no"
    volumes:
    - type: bind
      source: ./config
      target: /config
      bind:
        create_host_path: true
